apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2022-02-09T06:51:46Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: rest-api
  name: rest-api
  namespace: default
  resourceVersion: "2076"
  uid: a492acf2-7d80-45d3-9258-cf360b276daa
spec:
  clusterIP: 10.0.182.177
  clusterIPs:
  - 10.0.182.177
  externalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31288
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: rest-api
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 20.84.12.104
